### ISSUE TITLE
Chrome (Android) is always reporting `redirectionTime` as 0

### ISSUE THREAD

**Issue by acreskeyMoz** [mozilla/browsertime#41]
`redirectionTime` is always reported as 0 by Chrome for android.
Not sure where the problem is.
This is found in (data[0]['statistics']['timings']['pageTimings']['redirectionTime'])

This is a useful performance metric.

**Comment by dpalmeiro** [comment]
This is coming from Chrome, not any problem in browsertime.  

connectEnd: 1569344374609
connectStart: 1569344374535
domComplete: 1569344382023
domContentLoadedEventEnd: 1569344379583
domContentLoadedEventStart: 1569344379583
domInteractive: 1569344377271
domLoading: 1569344375871
domainLookupEnd: 1569344374535
domainLookupStart: 1569344374493
fetchStart: 1569344374492
loadEventEnd: 1569344382107
loadEventStart: 1569344382023
navigationStart: 1569344374426
redirectEnd: 0
redirectStart: 0
requestStart: 1569344374609
responseEnd: 1569344376464
responseStart: 1569344375846
secureConnectionStart: 1569344374567
unloadEventEnd: 0
unloadEventStart: 0

**Comment by acreskeyMoz** [comment]
Interesting, that's what I'm also seeing from `window.performance.getEntriesByType("navigation");` on Chrome Desktop and Chrome Android.
If there isn't anything to be done in Browsertime then shall we close this?
I'll log this against against Chromium

**Comment by acreskeyMoz** [comment]
Hmm... and as I go to log this against Chromium it's now working
`window.performance.getEntriesByType("navigation")[0]` as a floating point milliseconds, and `performance.timing` as timestamps.

I'm going to close this against browsertime.

I'm not sure that this is worth the time for me to investigate further in Chromium.
