### ISSUE TITLE
allow visiting about: pages

### ISSUE THREAD

**Issue by tarekziade** [mozilla/browsertime#57]
For some testing, I need to visit about:crashparent, and more generally, I don't think we should restrict BT to http://

Let's make it possible to visit about: pages via BT.
This requires a few fixes in cli.js and a few other spots that make the assumption that anything that is not starting with "http:" is a file

**Comment by tarekziade** [comment]
We can't do this yet via geckodriver. we can't change to the chrome context because it would replace the browser.xul

**Comment by ncalexan** [comment]
> We can't do this yet via geckodriver. we can't change to the chrome context because it would replace the browser.xul

There's another layer (at least one) in here for Android: GV itself and/or the vehicle blocks certain load types.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1582606 for `data:`, but I think the situation is similar for `about:`.
